Add Pizza Clause (11.4)
UQComputingSociety/constitution pull request #41
Opened 2022-09-16 05:56 UTC by Thomas-Malcolm

Co-Authored-By: Tom <52238845+Thomas-Malcolm@users.noreply.github.com>

2022-09-16 05:58 UTC, nicklambourne requested changes
![communityIcon_mcqfvwckzgk41](https://user-images.githubusercontent.com/9084563/190567011-abccaf48-733e-4514-bfd4-31f35127ce5d.jpg)

2022-09-16 06:26 UTC, JamesDearlove requested changes
We're gonna need some justification here team 🍕 

Also, I'd argue that garlic bread should be mandated in the constitution instead of Hawaiian pizza.

2022-09-16 06:39 UTC, katrinafyi commented
I thought garlic bread was deprecated in favour of the so-called cheesy garlic scrolls.

2022-09-16 06:41 UTC, sannibunny requested changes
As a vegetarian I am offended that the mandated pizza has meat. As a human, I am offended by pineapple on pizza. I will be organising a coup shortly.

2022-09-16 06:42 UTC, bradleysigma commented
> Australian Canadian Hawaiian Pizza.

2022-09-16 10:01 UTC, 49Indium requested changes

2022-09-16 10:01 UTC, 49Indium commented on constitution.md
> +* where procuring a Hawaii\[a\]n pizza from Canada is unfeasible, a substitute pizza originating from an establishment in Australia will suffice, provided that it meets the other requirements in 11.4
The phrase "a substitute pizza originating from an establishment in Australia will suffice, provided that it meets the other requirements in 11.4" is a bit concerning. There are no other requirements in 11.4, as the toppings listed are only "traditionally" supplied and the Canadian origin can be bypassed. Nothing is stopping UQCS executive from calling a meat-lovers pizza ("originating from an establishment in Australia") by the term "Hawaian".

2022-10-06 10:15 UTC, JamesDearlove commented
Tabled

2023-10-05 08:24 UTC, LimaoC commented
Withdrawn at 2023 AGM.

2023-10-05 08:24 UTC, closed without merging